public with sharing class StaticVar {

	public static boolean dc_homepage = false; 	
	public static boolean dc_rewardsearch = false; 
	public static boolean dc_rewarddetail = false; 
	public static boolean dc_claimreward = false; 
	public static boolean dc_partner = false; 
	public static boolean dc_faq = false;
 	public static boolean ListPartners = false; 
 	public static boolean RewardDetails = false; 
 	public static boolean ClaimReward = false; 
 	public static boolean oldiever = false; 
 	public static string title = 'IAVA - RuckSack';

}